export const ERROR_CODES = {
  UNAUTHORIZED: "UNAUTHORIZED_ACCESS",
  FORBIDDEN: "FORBIDDEN",

  NOT_FOUND: "RESOURCE_NOT_FOUND",

  INTERNAL: "INTERNAL_SERVER_ERROR",
  VALIDATION: "VALIDATION_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
} as const;
export type ErrorCodeType = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];